### ISSUE TITLE
问题依然存在

### ISSUE THREAD

**Issue by XingDunguo** [StevenBuglione/spring-boot-2-snakeyaml2-upgrade#1]
将本项目打成jar后，其他项目再依赖这个jar，启动依然报：method <init>()V not found

**Comment by StevenBuglione** [comment]
The purpose of the provided example is to illustrate the process of overwritting the AutoConfigured bean, specifically the YamlPropertySourceLoader, for compatibility with snakeyaml 2.0. It's important to note that simply compiling this application into a jar file and integrating it into your project will not suffice. To ensure proper functionality, it is necessary to individually implement the necessary modifications in each application.
